### PR TITLE
Add @gvanrossum and me to typing experts list

### PR DESCRIPTION
**Pull request by ilevkivskyi**

### CODE REVIEW

**Comment by ezio-melotti** [comment]
@ilevkivskyi, is @gvanrossum fine with the addition?
He recently requested to be removed as asyncio expert (#143).

**Comment by ilevkivskyi** [comment]
@ezio-melotti 
> @ilevkivskyi, is @gvanrossum fine with the addition?
He recently requested to be removed as asyncio expert (#143).

I don't know for sure, this is why I @ tagged him in the title. But I assume yes, taking into account his recent interest in this module.

**Comment by ezio-melotti** [comment]
In that case I'd prefer to wait for him to reply before merging the PR.
Even though he is interested in the module, the expert list is used to populate the nosy field of the bug tracker, and he might not want that.

**Comment by gvanrossum** [comment]
Yes it's fine! :-)

**Pull request merged**
