### PR TITLE
Use python-docs-theme

### LINKED ISSUE #351: Migrate devguide to python-docs-theme
For maintainability and consistency, migrating to https://github.com/python/python-docs-theme makes good sense.

fyi @ned-deily @jonparrott

### PR DESCRIPTION
**Pull request by jonparrott**
Fixes #351 

You can see a build of this [here](http://temp.theadora.io/devguide/index.html).

### CODE REVIEW

**Comment by Mariatta** [comment]
Just noticed that travis failed after I approved 😅

**Comment by jonparrott** [comment]
Aww. Will fix when I get back to a computer

**Comment by jonparrott** [comment]
Okay, Travis is passing. :)

**Comment by Mariatta** [comment]
Thanks! I looked at several pages and everything looks good. Let's deploy 😁

**Comment by Mariatta** [comment]
It's live!

**Comment by jonparrott** [comment]
Yay!

**Comment by willingc** [comment]
Thank you @jonparrott and @Mariatta :sparkles: 🐍

**Pull request merged**
