### PR TITLE
Updated the location of the dev guide repo

### PR DESCRIPTION
**Pull request by evelynmitchell**

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

Unfortunately we couldn't find an account corresponding to your GitHub username at [bugs.python.org](http://bugs.python.org/) (b.p.o). If you don't already have an account at b.p.o, please [create one](http://bugs.python.org/user?@template=register) and make sure to add your GitHub username. If you do already have an account at b.p.o then please go there and under "Your Details" add your GitHub username.

And in case you haven't already, please make sure to sign the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA); we can't legally look at your contribution until you have signed the CLA.

Once you have done everything that's needed, please reply here and someone will verify everything is in order.

**Comment by evelynmitchell** [comment]
Move to github needed to be reflected in dev guide.

**Comment by evelynmitchell** [comment]
I have signed the CLA.

**Comment by berkerpeksag** [comment]
Thanks for the PR. https://github.com/python/cpython is a read-only mirror of https://hg.python.org/cpython/ We haven't switched to Git yet.

**Comment by ncoghlan** [comment]
To expand on Berker's answer a bit - *this* repo (for the devguide) has migrated, but the main CPython repo (which is the one referenced by the link being amended in this PR) won't move until later in the year (there are a lot more processes linked to the CPython repo, so moving it is a more involved process than the support repos like the dev guide)

**Comment by bitdancer** [comment]
Also note that there is a branch in this repo for working on the (eventual) cpython-on-github version of this guide.

**Pull request closed without merging**
