### PR TITLE
Serves static content from docs.python.org.

### PR DESCRIPTION
**Pull request by lisroach**
Except for the collapsible sidebar, which requires a change in Sphinx iteself.

Also changed hover color for header links.

### CODE REVIEW

**Comment by berkerpeksag** [comment]
Sorry for the delay. I'm reviewing this now.

**Comment by brettcannon** [comment]
@berkerpeksag is your review done? Otherwise I'm tempted to accept this PR as-is.

**Comment by lisroach** [comment]
Thank you!

**Comment by zware** [comment]
Thanks, @lisroach!  I changed the hover color to `#eee`, otherwise the patch was great.

**Comment by brettcannon** [comment]
We should probably either do a merge into `github` or do a cherry pick.

**Comment by zware** [comment]
Should already be done.  There were also a few other outstanding changes on `master` that were also merged.

**Comment by willingc** [comment]
Thanks @zware for the work on merging the outstanding changes on master 😄  I've been slammed with Jupyter stuff lately. Thanks @brettcannon for keeping this on your radar 🎯 :smile:

@lisroach Congrats! Thanks and great to see this merged: :tada:

**Pull request merged**
