### PR TITLE
Add entry for Jason R. Coombs based on his best recollection.

### LINKED ISSUE #455: No entry for  Jason R. Coombs in developers.rst
Hi,

I can see that Jason is a core-dev but I don't find any entry in developers.rst.

Thank you

### PR DESCRIPTION
**Pull request by jaraco**
Fixes #455.

### CODE REVIEW

**Comment by jaraco** [comment]
@brettcannon I vaguely recall that you were the approving member for the distutils2 working group at PyCon 2010. Or maybe it was 2011? I'm pretty sure it was Atlanta. Do you recall? Are there other records we can use to validate the declaration?

**Comment by brettcannon** [comment]
I would just look at when the oldest commit was and which dates aligns the best. Once you do that then feel free to merge.

**Comment by jaraco** [comment]
I don't believe I pushed any commits during that sprint, despite being granted access.

I do see my first major contribution in d40e6f70a5, which was committed as part of bpo-1578269. My first direct commit seems to be fee7745ebb, which would have been after PyCon 2011. So maybe that was the correct year. At the very least, we know it could not have been later than that. I'll update the PR accordingly.

**Comment by jaraco** [comment]
This renewed commit assumes that PyCon 2011 was the place where the change was granted. That aligns better with the history of commits.

**Pull request merged**
