### PR TITLE
Update the status of Python 3.2 to "end-of-life"

### PR DESCRIPTION
**Pull request by akitada**

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

Unfortunately we couldn't find an account corresponding to your GitHub username at [bugs.python.org](http://bugs.python.org/) (b.p.o). If you don't already have an account at b.p.o, please [create one](http://bugs.python.org/user?@template=register) and make sure to add your GitHub username. If you do already have an account at b.p.o then please go there and under "Your Details" add your GitHub username.

And in case you haven't already, please make sure to sign the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA); we can't legally look at your contribution until you have signed the CLA.

Once you have done everything that's needed, please reply here and someone will verify everything is in order.

**Comment by akitada** [comment]
I have signed the CLA.

**Comment by berkerpeksag** [comment]
This is not yet EOL, because we wait for 3.2.7 release.

**Comment by brettcannon** [comment]
@birkenfeld is there still going to be a 3.2.7 release?

**Comment by matrixise** [comment]
@berkerpeksag is there a plan for 3.2.7 ? because when we read the PEP 392 (https://www.python.org/dev/peps/pep-0392/#id19) the date was 27th Feb 2016 and we are in October 2016. What is the status about the future 3.2.7 ? and what's the idea of @birkenfeld about this point ?

**Comment by berkerpeksag** [comment]
I'd say let's merge this. 3.2.7 is going to be a source-only release anyway and I don't see a reason to bug Georg about this (he already spent a lot of time maintaining 3.2 and 3.3) If anyone wants 3.2.7, the only thing to do different is use the 3.2 branch instead of a release tarball.

@brettcannon what do you think?

**Comment by ned-deily** [comment]
As of a couple of weeks ago, @birkenfeld was still planning to do a final 3.2.7.  But I'd say it's OK to merge this; the data can be updated later.

**Comment by matrixise** [comment]
in this case, who can merge it ? thanks

**Comment by ned-deily** [comment]
This should also be merged to the master branch.

**Comment by brettcannon** [comment]
I used the new cherry-pick steps that @soltysh wrote and created 4c9dad2 for backporting to the `master` branch. Worked seamlessly!

**Pull request merged**
