### PR TITLE
Update README.rst with doc changes

### PR DESCRIPTION
**Pull request by SmashedFrenzy16**
----
:books: Documentation preview :books:: https://cpython-devguide--1105.org.readthedocs.build/

### CODE REVIEW

**Comment by CAM-Gerlach** [comment]
Sorry, but it is not clear that any of these trivial changes are a clear, substantive improvement over the previous text, nor is the reason for making them described above.

Furthermore, it seems this user's homepage is an exercise in self-aggrandizement, and of their hundreds of PRs to projects they don't themselves own or control, all of the recent ones I could find were trivial and generally spammy in nature, with no description and rarely much or any response when asked to explain their changes. Most fell into one of two categories:

* Those with similar title and purpose to this, similar titles to this, e.g. "Fix formatting in README.rst", "Update README.rst with documentation changes", which made a handful of similarly trivial changes that are of little or even negative utility, e.g. https://github.com/google/zx/pull/610

* Those that claim to "optimize" the code in question, none of which seem to offer anything but trivial speedups, but often change the semantics or even obviously break the code e.g. https://github.com/google/oss-fuzz-vulns/pull/33

* Other PRs like randomly renaming files e.g. https://github.com/openai/gym/pull/3190, or merging in a ton of random changes with no explaination, e.g. https://github.com/chesslablab/react-chess/pull/415

This is not a new user, as they've been doing this very same thing for years and years despite hundreds of these spam PRs being closed or their reasons questioned, have shown no attempt to meaningfully contribute beyond the trivial, and it seems very clear that their "contributions" are calculated primary to benefit themselves and not others. On the other hand, they do appear to be a real human unlike the many spambots we get, as they occasionally do respond and even more occasionally update their PRs, and they've been doing it since well before generative AIs were publicly available. 

Therefore, while I'm not sure this is worth reporting to GitHub (though I was tempted), it could be something the @python/organization-owners could take a look at.

@SmashedFrenzy16 , do you have anything to say for yourself?

**Comment by SmashedFrenzy16** [comment]
@CAM-Gerlach, we are not spam bots. As you can see from my profile, I have been gradually building up my projects. CodeMaster7000 joined later on, and had more projects since he had been coding from before he joined. So he had more projects at the launch of his GitHub. Furthermore, you might want to check our other social media accounts. For example, if you check my Twitter and both of our YouTube channels, you can evidently see no marks of spam. We are just two aspiring developers who want to change the world. As both of us are friends, we might tend to get a bit annoyed at each other and perhaps copy each other for various reasons (although this could also be a mistake that we copy each other). But we intend no harm, and are promptly fixing any repetitive behavior we have. For example, we don't copy each other in PR companies as much anymore. But sometimes we both need inspiration from each other, so we might have the same project ideas but with different code, or same company, but different PR changes. Small PR changes are for our learning experiences and to get better at making PRs. The frequency of these have decreased as we make more code related PRs. Furthermore, I don't think spam accounts go throught the hassle of setting up sponsors so tediously to help the community. Spam bots also don't spell correctly and get banned on other platforms. Now I see you may regard this as a message that a spam bot made to support another, but I don't think this is the case as I have pure evidence to surround the fact that both of us are not bots. I understand your concern to stop GitHub being flooded with spam or other bad account types, but we simply are not bots. It would be more evident if we were. Also, more people would have picked up that we were spam bots if we were. But that does not present to be the case. I would like to end off with the fact that humans can make errors and that the changing to this README file's extension type might have been CodeMaster7000 not knowing the changes it would make. We both help each other to help learn different aspects of GitHub properly, and not everything can happen at once.

**Comment by SmashedFrenzy16** [comment]
This is a repeat on what i said at #1098 I am reiterating here as I am NOT a spam bot. I have made meaningful code contributions, including making a github readme trophy. I am here to help the community and fix minor changes as well.

**Comment by SmashedFrenzy16** [comment]
I am sorry if you find this trivial, I am cnstantly learning form my mistakes. Also, I don't participate in self-aggrandizement and boasting, because that is useless. I do want to help people, and that is also a fndemental of open-source. Some of my repositories are also learning experiences for me, and may be from a tutorial that I do. As I learn new languages, I tend to upload my progress. GitHub is a passion of mine, and I don't wish to boast or self-aggrandize. Please don't consider me to have bad intentions. I am currently trying to expand the usefullness of my PRs. Please understand that people are not machines or AI, hence they cannot do everything perfectly/instantly.

**Comment by ewdurbin** [comment]
hi. one does not need to a bot to produce spam, which distracts maintainers and wastes their time.

you do not need to make a case or defend yourself, consider taking time to ensure changes submitted are of substance, complete, explained well, and provided in good faith moving forward.

**Pull request closed without merging**
