### PR TITLE
list community platform (emscripten) supporters github id

### PR DESCRIPTION
**Pull request by pmp-p**
with github id of whose who stepped up in that thread https://discuss.python.org/t/im-stepping-down-as-sponsor-of-emscripten/41064/20

----
📚 Documentation preview 📚: https://cpython-devguide--1267.org.readthedocs.build/

### CODE REVIEW

**Comment by encukou** [comment]
@hoodmane, @rdb, @rth, @ryanking13: Please confirm that you'd like to be notified about Emscripten issues, and that we should -- as a courtesy -- seek for your opinion about related changes.

Emscripten remains an unsupported platform for now, but I'm trying to figure out how we should handle community-supported platforms. (More details on that here: https://discuss.python.org/t/44621)

**Comment by ryanking13** [comment]
> Please confirm that you'd like to be notified about Emscripten issues, and that we should -- as a courtesy -- seek your opinion about related changes.

Yes, I am okay with getting notified about emscripten issues. Thanks!

**Comment by rdb** [comment]
Yes, fine with me

**Comment by hoodmane** [comment]
Yes, thanks!

**Comment by rth** [comment]
Fine with me as well. Thanks @pmp-p and @encukou !

**Review by ezio-melotti — APPROVED** [review]

**Pull request merged**
