### PR TITLE
gh-821: Add/rename new types

### PR DESCRIPTION
**Pull request by za**
~WIP: still need to add the description.~

Refer to this merged PR:
https://github.com/python/bedevere/pull/419/files

Closes https://github.com/python/devguide/issues/821

### CODE REVIEW

**Comment by za** [comment]
Hi @ezio-melotti I've added the description using https://github.com/python/cpython/labels as the reference. Please check.

**Comment by AlexWaygood** [comment]
@za, FYI, if you include the phrase "Closes #821" or "Fixes #821" in your PR description, then issue #821 will be automatically closed when this PR is merged. That will mean that you won't have to ping a maintainer to manually close an issue after the PR has been merged :)

https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests

**Comment by za** [comment]
Hi @AlexWaygood Thanks! I've updated the PR description :-)

**Comment by ezio-melotti** [comment]
I'm going to close this since the name of labels don't match anymore and there are conflicts.  The list of labels is already being updated in another PR.  Thanks anyway for the PR!

**Pull request closed without merging**
