### PR TITLE
Add Karthikeyan to the developer log

### PR DESCRIPTION
**Pull request by brettcannon**

### CODE REVIEW

**Comment by brettcannon** [comment]
Sorry about the oversight, @tirkarthi !

**Comment by brandtbucher** [comment]
@brettcannon, perhaps you meant 2019 (not 2020)?

**Comment by tirkarthi** [comment]
Thanks Brett :)

**Comment by brettcannon** [comment]
@brandtbucher It's actually automatically generated from other data which I probably provided, so I'll assume I did the screw-up. 😄  I'll fix it in another commit.

**Pull request merged**
