### PR TITLE
Change "dir" to "directory"

### PR DESCRIPTION
**Pull request by aaronang**

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](https://bugs.python.org/) (b.p.o) to verify you have signed the CLA (this might be simply due to a missing "GitHub Name" entry in your b.p.o account settings). This is necessary for legal reasons before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


Thanks again to your contribution and we look forward to looking at it!

**Comment by willingc** [comment]
Hi @aaronang, Thanks for taking the time to fix this typo. If you sign the CLA, I will be able to review and merge.

**Comment by aaronang** [comment]
@willingc I did sign the CLA two days ago but my status hasn't changed yet on b.p.o.

**Comment by terryjreedy** [comment]
Status changes take a few days.  Let us know when it does.

**Comment by aaronang** [comment]
Status on BPO is still: "Contributor Form Received". Could someone check the progress?

**Comment by ncoghlan** [comment]
I've sent a follow-up query to contributors@python.org - submitted forms typically get reflected back into the bugs.python.org metadata within a couple of US business days (as indicated by a date showing up next to the "Contributor Form Received" entry), but that hasn't happened for you yet.

**Comment by aaronang** [comment]
@terryjreedy I thought I already did:

image

**Comment by terryjreedy** [comment]
Email ewa@python.org about filling in the contributor form part.  Make sure to tell her your tracker id.  She may find the signed form and fill it in, or she may tell you to sign it again.

**Comment by aaronang** [comment]
The status changed:

image

Is everything alright now?

**Comment by zware** [comment]
Yes, and merged :). Thanks, @aaronang!

**Comment by aaronang** [comment]
Thank you all for your help and patience 🙌

**Pull request merged**
