### PR TITLE
Document the "bpo-" prefix

### PR DESCRIPTION
**Pull request by brettcannon**

### CODE REVIEW

**Comment by Mariatta** [comment]
:thinking: Should the example in line 413 be updated too?
From
```
git commit -m '#12345: fix some issue.'
```
into
```
git commit -m 'bpo-12345: fix some issue.'
```

**Comment by brettcannon** [comment]
Yep, it should. I'll fix it shortly.

**Comment by Mariatta** [comment]
@brettcannon I already did it :sweat_smile: https://github.com/python/devguide/pull/100

**Comment by brettcannon** [comment]
Just noticed. :)

**Pull request merged**
