### PR TITLE
fix broken issue tracker link

### PR DESCRIPTION
**Pull request by blossomica**
Closes https://github.com/python/devguide/issues/156

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately our records indicate you have not signed the CLA. For legal reasons we need you to sign this before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://cpython-devguide.readthedocs.io/pullrequest.html#licensing) to rectify this issue.


Thanks again to your contribution and we look forward to looking at it!

**Comment by Mariatta** [comment]
Thanks for your first contribution to the devguide @blossomica 🎉 
Hope to see more contributions from you!

I personally witnessed @blossomica signed the CLA, so I'm bypassing the bot 😸

**Comment by blossomica** [comment]
@Mariatta - Thanks 😃

**Comment by willingc** [comment]
Way to go @blossomica! Congrats on the first contribution. Have fun sprinting with @Mariatta :D

**Comment by blossomica** [comment]
@willingc - Thank you :)

**Pull request merged**
