### PR TITLE
Add myself to devguide, docs, and turtle experts

### PR DESCRIPTION
**Pull request by willingc**
@brettcannon, @ncoghlan, and @Mariatta Please review. Moving forward I plan to focus on documentation and education elements of CPython. Thanks!

### CODE REVIEW

**Comment by Mariatta** [comment]
Thanks @willingc 
I believe something has to happen in b.p.o in order to get you added to the nosy list?

**Comment by matrixise** [comment]
@terryjreedy @Mariatta please, can I merge it ?

**Comment by Mariatta** [comment]
I don't have admin access in b.p.o. I think @brettcannon needs to first add @willingc to the nosy list for those elements. Then we can merge this :)

**Comment by terryjreedy** [comment]
This is a 'trivial' patch and does not need and should not have a bpo issue.  The green Squash and merge button is live for me, and I presume it would work, but I think Carol should merge this when she can, as proof that she can.

**Comment by brettcannon** [comment]
I actually don't know how the nosy lists are generated. @soltysh might now.

**Comment by soltysh** [comment]
I'll check and make sure you're added where needed :)

**Pull request merged**
