### PR TITLE
Recommend GitHub CLI for easier bootstrapping

### PR DESCRIPTION
**Pull request by jaraco**
As I was working on #943, I realized it might be easier to direct users to use the GitHub CLI instead of all of the manual steps.

Thoughts?

- Consider directing users to the GitHub CLI for easier bootstrapping.

### CODE REVIEW

**Review by ezio-melotti — COMMENTED** [review]
I don't think `gh` should be required.  It's fine documenting it as an alternative setup (here or in the bootcamp), but a regular setup that doesn't use `gh` should still be documented.

See also,:
* #861
* #882

**Comment by erlend-aasland** [comment]
I think promoting `gh` is a good thing. It is a great tool for our workflow.

**Comment by hugovk** [comment]
[Sphinx Inline Tabs](https://sphinx-inline-tabs.readthedocs.io/en/latest/) could be useful to show the two different options.

It's used on https://packaging.python.org/en/latest/tutorials/packaging-projects/ to select between Unix/macOS and Windows (and also Hatchling, setuptools, Flit and PDM):

* https://packaging.python.org/en/latest/tutorials/packaging-projects/#generating-distribution-archives
* https://packaging.python.org/en/latest/tutorials/packaging-projects/#creating-pyproject-toml

It's nice that you when you select one tab, it flips for the whole page:

image

image

Also used for example at https://pip.pypa.io/en/stable/getting-started/

**Comment by CAM-Gerlach** [comment]
Agreed that showing both options, one with a specific one wrapper tool and the more manual one with the "standard" tooling, would be helpful (I personally still use `hub` myself). And +1 for Sphinx inline tabs; with appropriate organization they allow showing alternatives while avoiding making the document longer and more confusing. We (Spyder) really need to adopt this ourselves in all our own docs that offer both `venv/pip` and `conda` environment and installation methods.

@hugovk is there a built-in way to link the tab choices, so that clicking on one will automatically switch all of them, or is that a custom extension on the packaging site? That definitely is a big boon for usability.

**Comment by hugovk** [comment]
@CAM-Gerlach Yes, it's built-in!

> * Synchronisation: Tabs with the same label all switch with a single click.

And see the demo at https://sphinx-inline-tabs.readthedocs.io/en/latest/

**Comment by ezio-melotti** [comment]
@jaraco, do you want to update the PR to use `sphinx-inline-tabs`?

**Comment by jaraco** [comment]
While I can see the value in using sphinx-inline-tabs, I worry that the maintenance burden is getting out of hand, especially considering that the docs exist in two places, so anything that happens probably needs to be duplicated, so duplicating the techniques would be a multiplier on the existing multiple. It's probably best to provide one technique. I wouldn't be opposed to someone adopting this diff to use sphinx-inline-tabs, but I'm not inclined to do it myself.

**Pull request closed without merging**
