### PR TITLE
help: Add link to Discourse instance

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Add note that IRC channel may not have history, and thus may not be easily searchable for newcomers.
(I could not easily find a discussion archive)

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

## Recognized GitHub username

We couldn't find a [bugs.python.org](https://bugs.python.org/) (b.p.o) account corresponding to the following GitHub usernames:

@EricCousineau-TRI

This might be simply due to a missing "GitHub Name" entry in one's b.p.o account settings. This is necessary for legal reasons before we can look at this contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.




You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

**Comment by EricCousineau-TRI** [comment]
Saw that there were some core development bits. It's not clear to me (as an outside) which form of communication is preferred.
Perhaps this? IRC > Discourse > Zulip > python-dev, at least for new questions?

It'd be great if there were some concrete pref, just so it's a bit less confusing for newcomers.

**Comment by Mariatta** [comment]
Zulip is no longer monitored by core devs.

Myself, I monitor only Discourse and python-dev. I know a few other core devs are on IRC. My personal recommendation is to make Discourse and python-dev be more prominent than IRC.

**Comment by EricCousineau-TRI** [comment]
Thanks! I've tried making the changes you suggested.

Can I ask if you have a suggested change for your office hours?
```
In Python's Zulip Chat, Core > Office Hour stream. A reminder will be posted to both Zulip and Mariatta's twitter account 24 hours before the start.
```

**Review by willingc — APPROVED** [review]
Thanks @EricCousineau-TRI for the contribution. Sorry for the delay in review and merge. I hope you will keep contributing to and using Python :snake:

**Comment by EricCousineau-TRI** [comment]
You're welcome! And yup, most certainly!

**Pull request merged**
