### PR TITLE
Move 'moved to' link to the end

### PR DESCRIPTION
**Pull request by hugovk**
These "Moved to [another-page#another-anchor]" links are a convenience to avoid linkrot:

image

---

Like at https://devguide.python.org/documentation/start-documenting/#style-guide, let's put them at end of the page.

So when reading through a page, the reader is not disturbed by a notice that some content has moved.

---

Before: https://devguide.python.org/#status-of-python-branches

After: https://cpython-devguide--1015.org.readthedocs.build/#status-of-python-branches

### CODE REVIEW

**Review by ezio-melotti — COMMENTED** [review]
I wonder if it would be better to put it before the full table of contents, since it looks a bit out of place having it after. :thinking:

**Comment by CAM-Gerlach** [comment]
Agreed with @ezio-melotti , I guess; otherwise seems LGTM

**Review by ezio-melotti — APPROVED** [review]

**Comment by hugovk** [comment]
Moved!

**Review by CAM-Gerlach — APPROVED** [review]
LGTM, thanks @hugovk

**Pull request merged**
