### PR TITLE
Clarify that PyUnstable macros use "PyUnstable" prefix

### PR DESCRIPTION
**Pull request by vstinner**
Discussion: https://github.com/python/cpython/pull/108440#issuecomment-1699105964

----
:books: Documentation preview :books:: https://cpython-devguide--1158.org.readthedocs.build/

### CODE REVIEW

**Comment by vstinner** [comment]
My previous abandoned PR for the Python documentation (``Doc/c-api/stable.rst``): https://github.com/python/cpython/pull/108710

cc @encukou

**Review by willingc — APPROVED** [review]
This looks like a reasonable clarification and guidance to me.

**Comment by willingc** [comment]
@vstinner I'm going to merge. If @encukou has a different viewpoint, we can always go back and modify. Thanks Victor.

**Comment by vstinner** [comment]
You're welcome Carol.

**Comment by encukou** [comment]
Sorry, I dropped the ball here. Thank you Carol for picking it up!

A technicality: I wouldn't call macros *symbols* -- it's better to reserve that term to the stuff that's exported from a `.so`/DLL. 

But with the list of examples, it's fine.

**Comment by vstinner** [comment]
> A technicality: I wouldn't call macros symbols -- it's better to reserve that term to the stuff that's exported from a .so/DLL.

**Pull request merged**
