### PR TITLE
Remove Martin von Loewis from the Expert List

### PR DESCRIPTION
**Pull request by haypo**

### CODE REVIEW

**Comment by haypo** [comment]
Martin von Loewis stopped to contribute to CPython in March 2013, longer than 4 years ago.

I see the Expert List as a list of people to contact to get a feedback. But Martin doesn't reply to Python emails anymore, so I suggest to remove him from this list.

**Comment by haypo** [comment]
Obvisouly, Martin Von Loewis remains mentioned in the list of core developers and other pages. My PR is restricted to the Expert List page.

**Comment by Mariatta** [comment]
Hm, perhaps as a courtesy we can personally ask him about this?

**Comment by brettcannon** [comment]
Even if Martin did come back, he's been gone long enough to not necessarily consider him an expert anymore. Plus half the things he's listed on have been taken over by others.

**Comment by haypo** [comment]
@brettcannon: Even if Martin did come back, he's been gone long enough to not necessarily consider him an expert anymore. Plus half the things he's listed on have been taken over by others.

For me, he remains one of the Unicode expert forever ;-)

**Pull request merged**
