### PR TITLE
Add Android platform to the experts list

### PR DESCRIPTION
**Pull request by FFY00**
We support Android, as best-effort, I believe. I don't think we have anyone leading it though, right?

### CODE REVIEW

**Comment by CAM-Gerlach** [comment]
IIRC, it was previously better-supported but the support has rotted over time without an active maintainer. Since we do have buildbots, if someone had signed up to maintain it, it could potentially be made a [Tier 3 platform per PEP 11](https://peps.python.org/pep-0011/#tier-3).

**Review by ezio-melotti — COMMENTED** [review]
I'd say to wait until Android is added to PEP 11 and/or has a maintainer before adding it to the platform list.

**Comment by CAM-Gerlach** [comment]
To note, the Experts index does include platforms that are supported by non-core devs and explicitly not supported per PEP 11; see [Petr's comment](https://github.com/python/devguide/issues/848#issuecomment-1200963008) on your #848 . However, IMO it should at least have an active maintainer of some sort (core dev or external) to be newly added there.

**Comment by hugovk** [comment]
On the other hand, someone may see the empty row and step up to fill it.

(But no strong opinion either way.)

**Review by Mariatta — APPROVED** [review]

**Comment by Mariatta** [comment]
I agree with adding it to the list as a category and letting people step up to fill it.

**Review by eamanu — APPROVED** [review]

**Pull request merged**
