### PR TITLE
include reference to create a pull request for the tests

### PR DESCRIPTION
**Pull request by DimitrisJim**
reword sentence to state how a pull request is required (and fix <patch> ref)

### CODE REVIEW

**Comment by DimitrisJim** [comment]
A very similar situation also exists in section [6.1. Helping with issues filed on the issue tracker](https://docs.python.org/devguide/docquality.html#helping-with-issues-filed-on-the-issue-tracker) while section [6.2. Proofreading](https://docs.python.org/devguide/docquality.html#proofreading

**Comment by berkerpeksag** [comment]
> A very similar situation also exists in section 6.1. Helping with issues filed on the issue tracker, I'll add a PR for that too if needed.

Good catch, thanks! Could you add another commit to this one instead?

**Comment by DimitrisJim** [comment]
Added the commit. Also took the liberty of mentioning how simple typos don't actually need an issue created for them.

**Comment by berkerpeksag** [comment]
Thanks!

**Pull request merged**
