### PR TITLE
Update URL to buildbot console.

### PR DESCRIPTION
**Pull request by levlaz**
Existing URL 404's.

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately our records indicate you have not signed the CLA. For legal reasons we need you to sign this before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


Thanks again to your contribution and we look forward to looking at it!

**Comment by levlaz** [comment]
I signed the SLA, and my profile on bugs.python.org now reflects this. :)

**Comment by zware** [comment]
Thanks for the patch!

There are a lot of buildbot-related updates that need to be made to the devguide since we upgraded to Buildbot 0.9.x; PRs for issue #290 are very welcome if you're interested :)

**Comment by levlaz** [comment]
@zware amazing, I will look into #290 and help out where I can!

**Pull request merged**
