### PR TITLE
Remove Guido as an asyncio expert

### PR DESCRIPTION
**Pull request by brettcannon**
Request was made by email.

### CODE REVIEW

**Comment by zware** [comment]
Also removed from auto-nosy on the tracker.

**Comment by brettcannon** [comment]
@zware thanks! How does one do that on the tracker?

**Comment by zware** [comment]
@brettcannon https://bugs.python.org/component to look up the component ID (or you can just edit it on that page), then https://bugs.python.org/component30 is asyncio.  Must have Coordinator role or greater to change it.

**Comment by gvanrossum** [comment]
Thanks!

**Pull request merged**
