### PR TITLE
Fix grammar in core dev motivations

### PR DESCRIPTION
**Pull request by rshah713**
Fix minor grammar changes in `motivations.rst` for core-developers.

### CODE REVIEW

**Comment by erlend-aasland** [comment]
cc. @python/proofreaders

**Comment by AA-Turner** [comment]
I'd hesitate to edit some of these as they're written by individuals.

A

**Comment by rshah713** [comment]
Completely understandable. I tried to keep my edits to grammar-only in order to not change the intended meaning of the original content. If this is still an undesired change, let me know what you'd like to salvage from this PR and I can revert the rest of the changes. Thanks!

**Comment by mwichmann** [comment]
The term "open source" (two words, sometimes initial caps but more often not) is in far more widespread usage than the hyphenated form.  This part of the change at least should be reverted.

Don't know if you'd consider these definitive, but see:
* https://opensource.com/resources/what-open-source
* https://www.redhat.com/en/topics/open-source/what-is-open-source
* https://en.wikipedia.org/wiki/Open_source
* https://www.ibm.com/topics/open-source

**Comment by JelleZijlstra** [comment]
None of the changes in the current PR seem like clear improvements.

**Comment by AlexWaygood** [comment]
> None of the changes in the current PR seem like clear improvements.

I agree; these mostly seem like matters of style to me. Some of these I prefer, some not so much, but none of the bits that are being changed seem "obviously wrong" enough to be worth changing.

Thanks for the PR, @rshah713, but I think we'll decline this one :)

**Review by CAM-Gerlach — COMMENTED** [review]
Just chiming in, as a technical writer and copyeditor. As others have mentioned, these changes are to bios written by individual people about themselves, to which only changes that are both unambiguously errors and clearly necessary should be proposed, and they are all trivial punctuation tweaks, none of them meaningfully change the grammar, as the title would imply.

Furthermore, as other imply, the hyphen changes are either net ≈nuetral or contradict common usage, and both comma removals are pretty clear regressions that harm phrasing and readability without any plausible benefit.

As some advice. It would be much more helpful if you could direct future contributors toward more meaningful fixes and improvements in the tutorials, how-tos and reference docs, rather than trivial punctuation nitpicks in self-written bios—or, offer to help with an open issue. I'm sure there's plenty of content which could use actual proofreading :)

**Comment by rshah713** [comment]
Thanks @CAM-Gerlach, @AlexWaygood and all for the review. Completely agree with the above points mentioned and will keep it in mind for future PRs. Grateful for the opportunity to contribute to such a powerful project :)

**Pull request closed without merging**
