### PR TITLE
Consistently use 'gc_ref' in the garbage collector docs

### PR DESCRIPTION
**Pull request by pablogsal**
Closes: #1026

### CODE REVIEW

**Review by gvanrossum — APPROVED** [review]

**Comment by gvanrossum** [comment]
Oh, maybe we should consistently use `gc_refs`? In gcmodule.c there's a variable named that and mentioned frequently in docs.

**Comment by JelleZijlstra** [comment]
There is a diagram somewhere that says `gc_ref` and Pablo said somewhere he didn't want to redraw it.

**Comment by CAM-Gerlach** [comment]
> There is a diagram somewhere that says `gc_ref` and Pablo said somewhere he didn't want to redraw it.

In https://github.com/python/devguide/issues/1026#issuecomment-1382896781 , BTW

**Comment by pablogsal** [comment]
If I manage to get some time I can give a go at doing the images again but meanwhile I will merge this. Thanks for the review!

**Pull request merged**
