### PR TITLE
Add Mariatta Wijaya as a core dev

### PR DESCRIPTION
**Pull request by brettcannon**

### CODE REVIEW

**Comment by willingc** [comment]
Congrats!!! Thanks @brettcannon.

**Comment by Mariatta** [comment]
I'm ecstatic!! :laughing:
Thanks @brettcannon and @willingc :tada:

**Comment by pfmoore** [comment]
Congratulations and welcome, @Mariatta !!!

**Comment by Vgr255** [comment]
Congratulations @Mariatta !!

**Comment by orsenthil** [comment]
Congratulations, @Mariatta . Looking forward to your contributions to core. Thank you!

**Pull request merged**
