### PR TITLE
Typo fix

### PR DESCRIPTION
**Pull request by cgl**

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](http://bugs.python.org/) (b.p.o) to verify you have signed the CLA. This is necessary for legal reasons before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://cpython-devguide.readthedocs.io/pullrequest.html#licensing) to rectify this issue.


Thanks again to your contribution and we look forward to looking at it!

**Comment by Mariatta** [comment]
This is trivial so CLA is not needed.
Thanks @cgl and congrats on your first contribution to the Dev Guide 🎉

**Comment by willingc** [comment]
Congrats @cgl :cake:

**Comment by cgl** [comment]
Thanks @the-knights-who-say-ni , I signed the agreement, soon it will be processed.

@Mariatta @willingc thank you very much, great to receive a warm welcome

**Pull request merged**
