### PR TITLE
i think this might help

### PR DESCRIPTION
**Pull request by Caesar1N**
this might help save some time .

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

## Recognized GitHub username

We couldn't find a [bugs.python.org](https://bugs.python.org/) (b.p.o) account corresponding to the following GitHub usernames:

@Caesar1N

This might be simply due to a missing "GitHub Name" entry in one's b.p.o account settings. This is necessary for legal reasons before we can look at this contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.




You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

**Comment by encukou** [comment]
This looks like another spam PR for @DigitalOcean's Hacktoberfest. See also https://blog.domenic.me/hacktoberfest/
If it's an actual honest attempt to help, please correct me.

**Comment by terryjreedy** [comment]
I agree with closing.  Both files appear to be unedited templates cut and pasted from somewhere else.  Any addition to out CI should first be discussed on an issue.  CPython already gets security scans on other sites.

**Comment by Caesar1N** [comment]
I was trying to be proficient with git buddy , I'm a newbie .
Sorry about that if it felt like a spam.

**Comment by Mariatta** [comment]
You can practise using git/GitHub on your own personal repository.
Review Hacktoberfest's quality standard before making additional PRs: https://hacktoberfest.digitalocean.com/details#quality

**Comment by Caesar1N** [comment]
Okay , sorry for the inconvenience . I'll do that . Thanks 👍

**Pull request closed without merging**
